dase_fft.c: fftgen.awk
	echo 3 | awk -f $< > dase_fft8.c
	echo 4 | awk -f $< > dase_fft16.c
	echo 5 | awk -f $< > dase_fft32.c
	echo 6 | awk -f $< > dase_fft64.c
	echo 7 | awk -f $< > dase_fft128.c
	echo 8 | awk -f $< > dase_fft256.c
	echo 9 | awk -f $< > dase_fft512.c
	echo 10 | awk -f $< > dase_fft1024.c
	echo 11 | awk -f $< > dase_fft2048.c

